# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('highlighted', models.BooleanField(default=False, verbose_name='highlighted')),
            ],
            options={
                'verbose_name_plural': 'posts',
                'verbose_name': 'post',
            },
        ),
    ]
