"""
Django settings for djangozh project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', False)

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',

    # third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.weibo',
    'crispy_forms',
    'taggit',
    'django_comments',
    'notifications',
    'captcha',
    'mptt',
    'actstream',
    'robots',
    "anymail",

    # local apps
    'users',
    'forum',
    'replies',
    'categories',
    'covers',
]

COMMENTS_APP = 'replies'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = 'media/'
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_ADAPTER = 'users.adapter.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'users.adapter.SocialAccountAdapter'
SOCIALACCOUNT_EMAIL_VERIFICATION = False
SOCIALACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_FORMS = {
    'login': 'users.forms.LoginForm',
    'signup': 'users.forms.SignupForm',
    'reset_password': 'users.forms.ResetPasswordForm',
    'add_email': 'users.forms.AddEmailForm',
}
ACCOUNT_LOGOUT_ON_GET = True
CRISPY_TEMPLATE_PACK = 'bootstrap4'

MARKDOWN_EXTENSIONS = [
    'markdown.extensions.fenced_code',
    'markdown.extensions.tables',
    'markdown.extensions.codehilite',
    TocExtension(slugify=slugify),
]

MARKDOWN_EXTENSION_CONFIGS = {}

BLEACH_ALLOWED_TAGS = ['a', 'img', 'br', 'strong', 'b', 'code', 'pre',
                       'p', 'div', 'del', 'dl', 'dt', 'dd', 'em', 'span', 'h1', 'h2', 'h3', 'h4',
                       'h5', 'h6', 'blockquote', 'ul', 'ol', 'tr', 'th', 'td',
                       'hr', 'li', 'u', 'embed', 's', 'table', 'thead', 'tbody',
                       'caption', 'small', 'q', 'sup', 'sub', ]

BLEACH_ALLOWED_ATTRIBUTES = {
    'a': ['href', 'title'],
    'abbr': ['title'],
    'acronym': ['title'],
    'div': ['class'],
    'span': ['class'],
    '*': ['id'],
    'img': ['src'],
}

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/user/login/'

NOTIFICATION_TEMPLATES = {
    '@': 'notifications/mention.html',
    'reply': 'notifications/reply.html',
    'recommend': 'notifications/recommend.html',
    'praise': 'notifications/praise.html',
    'favorite': 'notifications/favorite.html',
}

USE_PAGEDOWN = False

ADMINS = [('zmrenwu', 'pythonzhcn@163.com')]
SERVER_EMAIL = 'localhost@pythonzh.cn'

# robots
ROBOTS_USE_SITEMAP = True
